name: Dockerize and Push to Docker Hub

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build_and_push:
    name: Build Docker Image and Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Dockerize Application
        run: |
          docker build -t ZooManagementBackend:latest .
          docker images

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: docker tag ZooManagementBackend:latest nuduja/ZooManagementBackend:latest

      - name: Push Docker Image to Docker Hub
        run: docker push nuduja/ZooManagementBackend:latest